---
modules:
  collect_data:
    log_level: DEBUG
    data:
      input_folder: data/speech/input
      input_extensions:
        - .mp3
  transcribe_audios:
    log_level: DEBUG
    params:
      model: faster-whisper
      model_size: large-v2
      device: auto
      compute_type: auto
      beam_size: 5
      language: es
    data:
      output_folder: data/speech/output
      output_extensions:
        - .json