---
modules:
  collect_data:
    do_step: false
    log_level: DEBUG
    data:
      input_folder: data/speech/renfe380/wav
      max_files: -1
      input_extensions:
        - .WAV
  transcribe_audios:
    do_step: false
    log_level: DEBUG
    params:
      model: faster-whisper
      model_size: large-v2
      device: auto
      compute_type: auto
      beam_size: 5
      language: null
    data:
      output_folder: data/speech/renfe380_test/transcriptions
      output_extensions:
        - .json
  evaluate_transcriptions:
    do_step: true
    log_level: DEBUG
    params:
      reference_folder: ../innovation-renfe-dev/transcripts/anonymized/
      reference_extensions:
        - .txt
      metrics:
        - wer
        - cer
    data:
      output_folder: data/speech/renfe380_test/metrics_20250509
      output_extensions:
        - .json
        - .csv